### ISSUE TITLE
bug: Rust Build step failing for cloned repo

### ISSUE THREAD

**Issue by MetaverseRPN** [revoltchat/backend#324]
### What happened?

When attempting to build the backend from my own clone of this repo for use with self-hosting, the Rust build github workflow appears to fail from multiple migration steps:

` FAIL [   0.017s] revolt-database models::channel_webhooks::model::tests::crud

--- STDOUT:              revolt-database models::channel_webhooks::model::tests::crud ---

running 1 test
test models::channel_webhooks::model::tests::crud ... FAILED

failures:

failures:
    models::channel_webhooks::model::tests::crud

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 5 filtered out; finished in 0.01s

--- STDERR:              revolt-database models::channel_webhooks::model::tests::crud ---
thread 'models::channel_webhooks::model::tests::crud' panicked at crates/core/config/src/lib.rs:28:25:
called `Result::unwrap()` on an `Err` value: newline in string found at line 10 column 47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

        FAIL [   0.011s] revolt-database models::channels::model::tests::permissions_group_channel

--- STDOUT:              revolt-database models::channels::model::tests::permissions_group_channel ---

running 1 test
test models::channels::model::tests::permissions_group_channel ... FAILED

failures:

failures:
    models::channels::model::tests::permissions_group_channel

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 5 filtered out; finished in 0.00s

--- STDERR:              revolt-database models::channels::model::tests::permissions_group_channel ---
thread 'models::channels::model::tests::permissions_group_channel' panicked at crates/core/config/src/lib.rs:28:25:
called `Result::unwrap()` on an `Err` value: newline in string found at line 10 column 47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

------------
     Summary [   0.023s] 5/32 tests run: 0 passed, 5 failed, 0 skipped
        FAIL [   0.012s] revolt-config tests::it_works
        FAIL [   0.014s] revolt-database models::admin_migrations::model::tests::migrate
        FAIL [   0.013s] revolt-database models::bots::model::tests::crud
        FAIL [   0.017s] revolt-database models::channel_webhooks::model::tests::crud
        FAIL [   0.011s] revolt-database models::channels::model::tests::permissions_group_channel
error: test run failed`

**Comment by MetaverseRPN** [comment]
This has turned out to actually be a result of user error on our part. We were able to fix this by setting the repo based Revolt.toml back to the defaults. Apologizes for wasting your time.
